kind: pipeline
type: docker
name: test

trigger:
  event:
    - push
    - pull_request

steps:
  - name: test
    pull: if-not-exists
    image: golang:1.14
    commands:
      - go test -v ./...
      - go build

---
kind: pipeline
type: docker
name: deploy-prod

trigger:
  event:
    - tag

steps:
  - name: publish
    pull: if-not-exists
    image: plugins/gcr
    settings:
      registry: eu.gcr.io
      repo: toolsense/drone-github-comment
      storage_driver: aufs
      tags:
        - latest
        - ${DRONE_TAG}
    environment:
      GOOGLE_CREDENTIALS:
        from_secret: google_credentials
