kind: pipeline
name: test

trigger:
  event:
  - push

steps:
- name: test
  image: golang:1.14
  commands:
  - go test

- name: build  
  image: plugins/docker
  settings:
    repo: toolsense/drone-github-comment

---
kind: pipeline
name: publish

trigger:
  event:
  - tag

steps:
- name: publish
  image: plugins/gcr
  settings:
    registry: eu.gcr.io
    repo: toolsense/drone-github-comment
    storage_driver: aufs
    tags:
     - latest
     - ${DRONE_TAG}
  environment:
    GOOGLE_CREDENTIALS:
      from_secret: google_credentials
